### ISSUE TITLE
Cannot link project 1

### ISSUE THREAD

**Issue by allisonbelgarde** [Media-Ed-Online/intro-web-dev-2018spr-resources#26]
When I click Project 1 on my page it leads to a 404 error
<img width="481" alt="screen shot 2018-02-11 at 12 28 20 pm" src="https://user-images.githubusercontent.com/35909478/36077359-1c1726cc-0f27-11e8-81ec-ab4c7770a3df.png">

Is it something with my html for project 1?
<img width="1008" alt="screen shot 2018-02-11 at 12 29 12 pm" src="https://user-images.githubusercontent.com/35909478/36077374-49f27a74-0f27-11e8-868d-d2f36ae1d3d5.png">

Or the initial index.html?
<img width="690" alt="screen shot 2018-02-11 at 12 30 24 pm" src="https://user-images.githubusercontent.com/35909478/36077384-68747cd6-0f27-11e8-8095-af6a92a21bea.png">

Or something I need to change on github? I appreciate any help!

**Comment by JustineEvansUM** [comment]
Hey @allisonbelgarde! I'm wondering if you fixed this already? Your [/web-dev-hw/index.html](https://allisonbelgarde.github.io/web-dev-hw/) (which was just for fun) looks great, works great. "assignment-3" is dead because we haven't made one yet, but "project-1" and "test" are linking great.

**Comment by allisonbelgarde** [comment]
@JustineEvansUM oh weird it was not working for me earlier but is now! Thank you :)
