### ISSUE TITLE
Moodle Homework Link?

### ISSUE THREAD

**Issue by Jetfished** [Media-Ed-Online/intro-web-dev-2018spr-resources#3]
I am just getting https://moodle.umt.edu/ when I click on the Homework link. Have I missed a step?

**Comment by JustineEvansUM** [comment]
Hey @Jetfished. Nope, that was just a generic link to Moodle that I forgot to remove. You can find the assignment by clicking through the Moodle shell, or I'll just post the full location here: [https://moodle.umt.edu/course/view.php?id=19964#section-2](https://moodle.umt.edu/course/view.php?id=19964#section-2)

**Comment by Jetfished** [comment]
Thanks!
