### ISSUE TITLE
link back from pages to index

### ISSUE THREAD

**Issue by Jetfished** [Media-Ed-Online/intro-web-dev-2018spr-resources#44]
https://github.com/Jetfished/web-dev-hw/tree/master/assignment-3

I'm not sure why I can't get the pages in the pages file to link back to the index. I'm gonna sleep on it but if anyone has a suggestion ...

**Comment by ewilsey** [comment]
I know you already know, but just in case anyone else is also wondering. I was able to link back to my index.html by typing "../index.html"

**Comment by Jetfished** [comment]
thanks dawg
