### ISSUE TITLE
Issues with live site

### ISSUE THREAD

**Issue by CamJohnsen** [Media-Ed-Online/intro-web-dev-2018spr-resources#48]
I've pushed assignment 4 to GitHub but for some reason it's not loading my live site.  Clicking on the assignment 4 link located here: https://camjohnsen.github.io/web-dev-hw/ results in nothing, not even a 404 error.  I have my assignment 4 folder nested in my web-dev-hw folder so I'm not sure why it's not publishing to GitHub.  My HTML code has been posted to my repo, so if anyone can take it look at it and see if I'm missing something that'd be a huge help!

**Comment by Jetfished** [comment]
hi Cam, can you post a link to your repo?

**Comment by CamJohnsen** [comment]
https://github.com/CamJohnsen/web-dev-hw/tree/master/assignment-4

**Comment by Jetfished** [comment]
I don't see anything wrong with your code, maybe GitHub hasn't updated your repo.

**Comment by Jetfished** [comment]
but I'm not at my console, check your links.

**Comment by ChristmasLeon** [comment]
I am having the same problem. My live site disappeared on Github. I was trying to push my assignment-4 onto my live site then I found out, my live site has been replaced by our very first assignment page "My Intro to Web-Dev" 
I didn't change it. And I couldn't find my live site html as well.

**Comment by JustineEvansUM** [comment]
Hey @CamJohnsen; the only thing "wrong" is you never updated the the example index.html you made in training. I only did the first link with you; you'd need to update the others yourself. :)
<img width="478" alt="camj" src="https://user-images.githubusercontent.com/25491569/36938801-477b0406-1ee4-11e8-9235-d6f79dd1ff87.png">

The live site URL is working great: https://camjohnsen.github.io/web-dev-hw/assignment-4/

So all you'd need to do is go into the that root index.html and continue making your links:

````
      <a href="./test/about.html">Test</a><br />
      <a href="./assignment-3/index.html">Assignment 3</a><br />
      <a href="./assignment-4/index.html">Assignment 4</a><br />
      ETC...
```

**Comment by CamJohnsen** [comment]
Oh yeah, I completely forgot about that index!  Thanks!
