### ISSUE TITLE
Markdown Preview: Toggle

### ISSUE THREAD

**Issue by Jorpatterson** [Media-Ed-Online/intro-web-dev-2018spr-resources#5]
Any ideas as to why I am not pulling up Markdown Preview: Toggle? I am working on my first readme file and I get to step 5 and try to find the markdown Preview and I get nothing. If I type in Preview fully the only thing I get is Depreciation Cop: View. Any help would be greatly appreciated. Thanks in advance!

**Comment by crewsertay** [comment]
I think that you have to have a new file open before you can access the command palette. After you have a file open you can open the command palette with **Command-Shift-P** and then if you type in "Preview" it should pop up. If not the keyboard shortcut for the Markdown Preview is **Control-Shift-M**. Hope that helps! 
![Markdown Preview](https://user-images.githubusercontent.com/35877026/35477976-fbb3c038-038d-11e8-8491-d0e50348194c.png)

**Comment by Jorpatterson** [comment]
Got it! Thank you!

**Comment by JustineEvansUM** [comment]
@Jorpatterson I see you've re-opened this thread. Are you still having issues?

(Thank you, @crewsertay, for helping!)

**Comment by JustineEvansUM** [comment]
If not, please see post #6 . You may need to install the `markdown preview` package.

**Comment by Jorpatterson** [comment]
Ooops, I didn’t mean to reopen it. Thank you!
