### ISSUE TITLE
Media from soundcloud and youtube?

### ISSUE THREAD

**Issue by Kevinhnolan** [Media-Ed-Online/intro-web-dev-2018spr-resources#53]
Am i supposed to download the media from these sites? How do I get them into my Webdev hw folder?

**Comment by JustineEvansUM** [comment]
Hey, @Kevinhnolan;

You don't have to download any media, other than some album art. The self-hosted videos that you'll use have been provided on Moodle. For the streaming sites, you'll use the embed codes they provide.

**Comment by Kevinhnolan** [comment]
ohh okay, how do I access the embed code they provide?

**Comment by JustineEvansUM** [comment]
Here you go! [Media in iframes](https://media-ed-online.github.io/intro-web-dev/docs/topic-06/iframes-element-media/)

**Comment by Kevinhnolan** [comment]
Hey so I see how to embed the media in my .index file using <iframes> but it says to place my media (youtube vid) into my media folder...how do I do that?


Thanks!

________________________________

**Comment by Jetfished** [comment]
the only media needed for the media folder are the two animations provided in the materials folder. youtube will provide you with an embed code which will be like a little window into YouTube from your page.

**Comment by Kevinhnolan** [comment]
okay! thanks
