### ISSUE TITLE
Audio and video not showing up

### ISSUE THREAD

**Issue by galen-koon** [Media-Ed-Online/intro-web-dev-2018spr-resources#58]
I can't get my audio or video files to show up using the iframe tag. Any help would be appreciated.
Here is my code:
<!DOCTYPE html>
  <html lang="eng-US">
  </html>

  <head>
    <meta charset="UTF-8">
    <meta name="description" content="Fanfare">
    <meta name="author" content="Galen Koon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="magic city hippies, fanfare, music, lyrics">
    <style>
    body {
      text-align: center;
      }
    .container {
      width: 600px;
      margin: auto;
      padding: 20px;
      border: 1px solid black;
    }
    .lyrics p, pre {
      font-family: arial;
      font-size: small;
    }
    .contact {
      background-color: powderblue;
    }
    </style>

    <title>Fanfare</title>
  </head>

  <body>
    <div id="art" class="container">
      <h1>Fanfare</h1>
      <h2>Magic City Hippies</h2>
      <img src="./images/coverart.jpg" alt="magic city hippies coverart" title="Fanfare" width="600" height="600"/>
    </div>

    <div id="audio" class="container">
      <h2>Audio Track</h2>
      <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" scr="https://soundcloud.com/magiccityhippies/fanfare"></iframe>
    </div>

    <div id="audio" class="container">
      <h2>Music Video</h2>
      <iframe width="560" height="315" src="https://www.youtube.com/watch?v=ylA2OehiOfU" frameborder="no"></iframe>
    </div>

    <div id="lyrics" class="container lyrics">
      <h2>Song Lyrics</h2>
      <p>
        [Intro]
Reefer
Ya know, reefer madness
A city starved of fame, it’s the same old thang
Yes, lean with me, rock with me
Golden sodas, one to stock, one to rock
Yes it’s here that we announce this day of freedom
Charles Bronson, signing out
Here we go
</br>
</br>
[Verse 1]
I grew up on the East side, the Miami Beach side
Deep fried in greed life, clam bakes by the seaside
Tan legs wearing knee highs, sand shakes off them sweet thighs
Back in 99 when I was silver spoon fed
Pops had the Porsche, dollin’ out the bread
Johns on the salsa, gun against his head
I got divorced ya, cold as a corpse
But there ain’t enough stamps in your passport for this crash course
I passed the class, now let's fast forward
Blast from the grass out on the back porch
Cash in the dash, I went straight to the source
Quarts, call them escorts
I’ve been moving bodies like I’m using the force
Floating down the river like a water resort
</br>
</br>
[Interlude]
Never coming back, never coming back
Magic City stuck in my head
</br>
</br>
[Hook]
Holding out for the Hollywood bride
My tongue gets heavier later on in the night
Here’s another one for the dinner plate eyes
My tongue gets heavier later on in the night
Holding out for the Hollywood life
My tongue gets heavier later on in the night
Here's another one for the children of the times
My tongue gets heavier later on in the night
</br>
</br>
Tenacity, Susan
[?]
(My tongue gets heavier)
I'm in love with you
It's a real love
I know it
When I'm with you
It feels like I'm walking on electric air
</p>
    </div>

    <div id="copyright" class="container contact">

    </div>
</body>

**Comment by ewilsey** [comment]
Is this the iframe selection that YouTube gives you?
If YES: No clue. 
If NO: Go to YouTube, and under the video where it says share, hit that and then on the bottom right you should see embed in blue text. Hit that and copy the link it gives you, then paste it in. Cheers.

**Comment by galen-koon** [comment]
That worked! Thank you! Do you have have any idea about the audio as well? I can't find an embed link on soundcloud @ewilsey

**Comment by galen-koon** [comment]
Just kidding @ewilsey I found it. I'm dumb

**Comment by galen-koon** [comment]
Thank you @ewilsey that did it! I appreciate the help

**Comment by ewilsey** [comment]
Right on, glad it worked out.

**Comment by galen-koon** [comment]
Yeah that was frustrating. Can't believe I wasn't using the right link. Really appreciate it
