### ISSUE TITLE
Text editor for Droid Turbo II

### ISSUE THREAD

**Issue by Jetfished** [Media-Ed-Online/intro-web-dev-2018spr-resources#7]
Atom is too big for my phone. Can anyone recommend a text editor for a mobile platform?

**Comment by goodrichnic** [comment]
Unfortunately, I've only had luck with code learning apps on mobile and those are never full-fledged text editors and cannot be relied upon as IDEs. But after doing a little research I did find [textbox.io](https://textbox.io/) which you could take a look at.

Let us know if you make that work, though I highly suggest using a computer. There are computer labs for your use in McGill Hall.

**Comment by Jetfished** [comment]
thanks, I have a working laptop I just enjoy writing on the go. I'll check out text box.

**Comment by JustineEvansUM** [comment]
Thanks @goodrichnic!

**Comment by Jetfished** [comment]
Just an update on mobile text editors. I've been using WordPad for Android. It saves as a .txt file but you do have the option of line numbering when writing. Anyway, problem solved.
